import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const MANIFEST = path.join(ROOT, 'site-asset-version.json');
const MODE = process.argv.includes('--write') ? 'write' : 'check';
const TOKEN_PLACEHOLDER = '__LOTBI_ASSET_VERSION__';
const TARGET_EXTENSIONS = new Set(['.js', '.mjs', '.css']);
const SOURCE_EXTENSIONS = new Set(['.html', '.js', '.mjs', '.css']);
const SKIP_DIRS = new Set(['.git', '.github', 'scripts', 'node_modules']);
const VERSION_RE = /^aset-[0-9a-f]{12}$/;

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
    if (entry.isDirectory() && SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(ROOT, full).replaceAll(path.sep, '/');
    if (entry.isDirectory()) {
      // Runtime avatar modules are cache targets; vendored three.js is sealed
      // and intentionally keeps import-map prefix semantics without queries.
      if (rel.startsWith('avatar-runtime/vendor')) continue;
      walk(full, out);
    } else {
      out.push(rel);
    }
  }
  return out;
}

function isRuntimeTarget(rel) {
  const ext = path.extname(rel);
  if (!TARGET_EXTENSIONS.has(ext)) return false;
  if (rel.startsWith('scripts/') || rel.startsWith('.github/')) return false;
  if (rel.startsWith('avatar-runtime/vendor/')) return false;
  return !rel.includes('/test') && !rel.endsWith('.test.js');
}

function isRuntimeSource(rel) {
  if (!SOURCE_EXTENSIONS.has(path.extname(rel))) return false;
  if (rel.startsWith('scripts/') || rel.startsWith('.github/')) return false;
  if (rel.startsWith('avatar-runtime/vendor/')) return false;
  return true;
}

function shouldVersionLocalAsset(assetPath) {
  const clean = assetPath.split('?')[0];
  if (!/\.(?:js|mjs|css)$/.test(clean)) return false;
  if (/^(?:https?:)?\/\//.test(clean)) return false;
  if (clean.includes('/avatar-runtime/vendor/')) return false;
  return true;
}

function withVersion(assetPath, version) {
  const [base] = assetPath.split('?');
  return shouldVersionLocalAsset(base) ? `${base}?v=${version}` : assetPath;
}

function rewriteRefs(source, version) {
  // Quoted local asset strings cover HTML href/src, static/dynamic ESM imports,
  // CSS-link assignments, worker registrations and test-fixture-like runtime
  // templates without touching prose that merely names "site-core.js".
  return source.replace(/(['"])((?:(?:\.\.?\/)|\/)?[A-Za-z0-9_./-]+\.(?:js|mjs|css))(?:\?v=[A-Za-z0-9._-]+)?\1/g,
    (match, quote, assetPath) => {
      if (!shouldVersionLocalAsset(assetPath)) return match;
      return `${quote}${withVersion(assetPath, version)}${quote}`;
    });
}

const allFiles = walk(ROOT);
const targets = allFiles.filter(isRuntimeTarget).sort();
const sources = allFiles.filter(isRuntimeSource).sort();

function expectedVersion() {
  const hash = crypto.createHash('sha256');
  for (const rel of targets) {
    const raw = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    // Canonicalization both inserts missing versions and removes the current
    // version value from the hash input, avoiding a self-referential digest.
    const canonical = rewriteRefs(raw, TOKEN_PLACEHOLDER);
    hash.update(rel, 'utf8');
    hash.update('\0');
    hash.update(canonical, 'utf8');
    hash.update('\0');
  }
  return `aset-${hash.digest('hex').slice(0, 12)}`;
}

const expected = expectedVersion();
const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));

if (MODE === 'write') {
  manifest.schema_version = 1;
  manifest.strategy = 'CONTENT_HASH_ASSET_SET';
  manifest.version = expected;
  manifest.note = 'Generated by scripts/asset_cache_version.mjs. Do not hand-edit version tokens.';
  fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');

  let changed = 0;
  for (const rel of sources) {
    const file = path.join(ROOT, rel);
    const before = fs.readFileSync(file, 'utf8');
    const after = rewriteRefs(before, expected);
    if (after !== before) {
      fs.writeFileSync(file, after);
      changed += 1;
    }
  }
  console.log(`ASSET-CACHE-WRITE version=${expected} files=${changed} targets=${targets.length}`);
  process.exit(0);
}

assert.equal(manifest?.schema_version, 1, 'site-asset-version.json schema_version must be 1');
assert.equal(manifest?.strategy, 'CONTENT_HASH_ASSET_SET', 'asset cache strategy must remain content-hash asset-set');
assert.match(String(manifest?.version || ''), VERSION_RE, 'asset cache version must be aset-<12 hex>');
assert.equal(manifest.version, expected,
  `asset content changed without regenerating URLs: run node scripts/asset_cache_version.mjs --write (expected ${expected})`);

const seen = new Map();
for (const rel of sources) {
  const file = path.join(ROOT, rel);
  const before = fs.readFileSync(file, 'utf8');
  const after = rewriteRefs(before, expected);
  assert.equal(before, after, `${rel}: local JS/CSS reference is missing generated version or uses a stale/manual token`);

  const refRe = /(['"])((?:(?:\.\.?\/)|\/)?[A-Za-z0-9_./-]+\.(?:js|mjs|css))\?v=([A-Za-z0-9._-]+)\1/g;
  let match;
  while ((match = refRe.exec(before))) {
    if (!shouldVersionLocalAsset(match[2])) continue;
    const key = path.posix.normalize(path.posix.join(path.posix.dirname(rel), match[2].replace(/^\//, '')));
    const tokens = seen.get(key) || new Set();
    tokens.add(match[3]);
    seen.set(key, tokens);
  }
}

for (const [asset, tokens] of seen) {
  assert.equal(tokens.size, 1, `${asset}: same module/style is referenced with multiple active version tokens: ${[...tokens].join(', ')}`);
  assert.equal([...tokens][0], expected, `${asset}: stale feature-name/manual cache token remains`);
}

for (const entry of ['index.html', 'auth/callback/index.html', 'auth/start/index.html']) {
  const source = fs.readFileSync(path.join(ROOT, entry), 'utf8');
  assert.ok(source.includes(`?v=${expected}`), `${entry}: generated asset version is not wired`);
}

console.log(`SITE-ASSET-CACHE-COHERENCE-01 PASS — version=${expected}, targets=${targets.length}, refs=${seen.size}`);
