import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const html = read('index.html');
const css = read('site-consumer-detail.css');
const ui = read('site-scam-shield.js');
const dialog = html.slice(html.indexOf('<dialog class="scam-dialog"'), html.indexOf('</dialog>', html.indexOf('<dialog class="scam-dialog"')));
assert.ok(dialog.indexOf('</header>') < dialog.indexOf('class="scam-dialog-inner"'), 'dismiss remains outside scroll body');
assert.match(css, /\.scam-dialog\[open\]\s*\{ display: flex; flex-direction: column;/);
assert.match(css, /\.scam-dialog-inner\s*\{[^}]*min-height: 0;[^}]*overflow-y: auto;/);
assert.match(css, /\.scam-dialog-header\s*\{[^}]*flex: 0 0 auto;/);
assert.match(css, /\.scam-input-kinds\s*\{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(css, /@media \(max-width: 600px\)[\s\S]*\.scam-input-kinds\s*\{ grid-template-columns: 1fr/);
assert.match(css, /::file-selector-button/);
assert.match(dialog, /data-scam-methods/);
assert.match(dialog, /data-scam-step hidden/);
assert.match(dialog, /data-scam-file-preview hidden/);
assert.match(dialog, /최대 10MB/);
for (const value of ['camera', 'photo', 'document', 'text', 'url']) assert.match(dialog, new RegExp(`data-scam-input-panel="${value}"`));
assert.match(dialog, /maxlength="20000"/);
assert.match(dialog, /<label for="scam-text">/);
assert.match(dialog, /<label for="scam-url">/);
assert.doesNotMatch(dialog, /data-scam-voice|data-scam-input-panel="voice"/);
assert.match(ui, /maxFileBytes = 10 \* 1024 \* 1024/);
assert.match(ui, /panel\.hidden = !visible/);
assert.match(ui, /methodChooser\.hidden = hasSelection/);
assert.match(ui, /checkStep\.hidden = !hasSelection/);
assert.match(read('site-scam-shield.css'), /\.scam-dialog \[hidden\]\s*\{\s*display: none !important/);
console.log('VERIFICATION_DIALOG_DESIGN_01 PASS — visual source guards; not analysis/API E2E');
