import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read = name => readFileSync(new URL(`../${name}`, import.meta.url), 'utf8');
const ui = read('site-festival-ui.js');
const css = read('site-consumer-detail.css');
const render = ui.slice(ui.indexOf('function renderProgramSurface('), ui.indexOf('function openProgramSurface('));
const load = ui.slice(ui.indexOf('async function openProgramFromCard('), ui.indexOf('async function openRegistrationFromCard('));
assert.match(ui, /onOpenProgram\(festival\.id, festival\)/);
assert.match(render, /if \(festival\.name\).*festival-program-event-name.*festival\.name/);
assert.match(render, /formatFestivalPeriod\(festival\)/);
assert.match(render, /if \(period\).*festival-detail-period.*period/);
assert.ok(render.indexOf('programSurface.appendChild(header)') < render.indexOf('if (!dateTabs.length)'), 'event context remains visible with no programs');
assert.ok(render.indexOf('if (loadFailed)') < render.indexOf('if (!dateTabs.length)'), 'failed reads cannot claim an empty program list');
assert.match(render, /message\.setAttribute\('role', 'alert'\)/);
assert.match(render, /retry\.addEventListener\('click', \(\) => \{\s*retry\.disabled = true;\s*retry\.textContent = '불러오는 중…';\s*onRetry\(\)/);
assert.match(load, /if \(token !== requestToken\) return/);
assert.match(ui, /function showList\(\)\s*\{[\s\S]*?\+\+requestToken;[\s\S]*?programSurface.hidden = true/);
assert.match(load, /loadFailed: failed \|\| !festival/);
assert.match(load, /festival \|\| \{\.\.\.listFestival, programs: \[\]\}/);
assert.match(load, /onRetry: \(\) => openProgramFromCard\(festivalId, listFestival\)/);
assert.doesNotMatch(load, /fetch\(|localStorage|createLifeActivity|addFestivalVisitToCalendar/);
assert.match(css, /\.festival-program-header\s*\{[^}]*border-bottom: 1px solid var\(--lotbi-border-default\)/);
assert.match(css, /\.festival-program-event-name\s*\{[^}]*overflow-wrap: anywhere/);
assert.match(css, /\.festival-manager \[hidden\]\s*\{ display: none !important;/, 'hidden flex surfaces must not leave blank space or expose stale detail content');
console.log('FESTIVAL_PROGRAM_CONTEXT_01 PASS — public event context, truthful empty/error states, retry and stale response guard; source checks only');
