import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {LIFE_SHORTCUTS} from '../site-consumer-sections.js';
const read = file => readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const source = read('site-consumer-sections.js');
const conversation = read('site-conversation.js');
const css = read('site-consumer-design.css');
assert.deepEqual(LIFE_SHORTCUTS.map(item => item.label), ['병원·의원', '약국', '축제·행사', '온누리상품권', '지역생활정보', '공과금 확인']);
assert.equal(new Set(LIFE_SHORTCUTS.map(item => item.id)).size, 6);
// Medical entries build their sentence from the form (LIFE-MEDICAL-CATEGORY-ENTRY-01).
// 축제·행사 and 온누리상품권 open their own surfaces (ONNURI-MERCHANT-01).
assert.ok(LIFE_SHORTCUTS.filter(item => !['festivals', 'onnuri'].includes(item.id) && !item.medical).every(item => typeof item.prompt === 'string'));
assert.match(LIFE_SHORTCUTS.find(item => item.id === 'bills').prompt, /등록할지/);
assert.ok(source.includes('제휴처 찾아 연결하기'));
for (const removed of ['사람 실종 신고', '반려동물 실종 신고', '112·119']) assert.ok(!source.includes(removed));
assert.doesNotMatch(source, /\bfetch\(|localStorage|sessionStorage|innerHTML|type = 'file'/);
assert.match(source, /mountLifeWallet\(\{root, authenticated, accountId, sessionExpiresAt\}\)/);
assert.match(source, /mountPeople\(host, initialSurface, counts =>/);
assert.match(conversation, /mountPersonCareManager\(\{sessionToken, root, initialSurface, onCountChange: reportCounts/);
assert.match(source, /role', 'tablist'/);
assert.match(source, /aria-selected/);
assert.match(source, /ArrowLeft.*ArrowRight.*Home.*End/);
assert.match(source, /disposed \|\| current !== generation/);
assert.match(source, /!authenticated/);
assert.match(source, /mounted\?\.dispose\?\.\(\)/);
assert.match(conversation, /onClose: \(\) => mounted\?\.dispose\(\)/);
assert.match(conversation, /mountPetFamilyManager\(\{sessionToken, root, subscription: serverSubscription/);
assert.match(conversation, /mountPersonCareManager\(\{sessionToken, root, initialSurface/);
assert.match(conversation, /onDraft: text => \{ closeSurface\(\); draft\(text\); \}/);
assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(css, /min-height: 44px/);
assert.match(css, /input:focus-visible/);
assert.match(read('site-scam-shield.js'), /scamOutsideBound/);
const scam = read('site-scam-shield.js');
assert.match(scam, /function restoreDialogFocus\(\)/, 'all close paths share visible-trigger focus restoration');
assert.match(scam, /visibleTrigger \? dialogTrigger : document\.querySelector\('\[data-mobile-nav-open\]'\)/, 'a hidden mobile trigger must fall back to the visible menu button');
assert.match(scam, /target\?\.focus\?\.\(\)/);
assert.match(scam, /dialog\.addEventListener\('close', restoreDialogFocus\)/, 'native close restores focus');
assert.match(scam, /dialog\.removeAttribute\('aria-modal'\);\s*restoreDialogFocus\(\);/, 'fallback close restores focus');
console.log('CONSUMER_SECTIONS_02 PASS — entry UX and safety source contracts, not backend E2E');
