import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const FIXTURE_REL='scripts/.life-wallet-document-save-fixture.html';const FIXTURE=path.join(ROOT,FIXTURE_REL);const PORT=23_000+(process.pid%20_000);const ORIGIN=`http://127.0.0.1:${PORT}`;
function browserPath(){for(const candidate of [process.env.CHROME_BIN,'C:/Program Files/Google/Chrome/Application/chrome.exe','google-chrome','chromium'].filter(Boolean)){if((candidate.includes('/')||candidate.includes('\\'))&&fs.existsSync(candidate))return candidate;const found=spawnSync(process.platform==='win32'?'where':'which',[candidate],{encoding:'utf8'});if(found.status===0&&found.stdout.trim())return found.stdout.trim().split(/\r?\n/u)[0]}throw new Error('Chrome/Chromium is required')}
const fixture=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/site-life-wallet.css"></head><body><main id="host"></main><pre id="result">pending</pre><script type="module">
const out=document.getElementById('result');const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));const wait=async(predicate,label)=>{for(let i=0;i<120;i+=1){const value=predicate();if(value)return value;await sleep(30)}throw new Error('timeout '+label+' states='+[...document.querySelectorAll('.wallet-scan-editor')].map(node=>node.dataset.scanState+':'+node.textContent).join('|'))};
try{
 let networkCalls=0;const realFetch=globalThis.fetch;globalThis.fetch=(...args)=>{networkCalls+=1;return realFetch(...args)};const realSend=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.send=function(...args){networkCalls+=1;return realSend.apply(this,args)};const realBeacon=navigator.sendBeacon?.bind(navigator);if(realBeacon)navigator.sendBeacon=(...args)=>{networkCalls+=1;return realBeacon(...args)};
 let closed=0;const realClose=ImageBitmap.prototype.close;ImageBitmap.prototype.close=function(){closed+=1;return realClose.call(this)};
 const source=document.createElement('canvas');source.width=480;source.height=320;const c=source.getContext('2d');c.fillStyle='#18212d';c.fillRect(0,0,480,320);c.beginPath();c.moveTo(70,55);c.lineTo(420,40);c.lineTo(440,275);c.lineTo(50,285);c.closePath();c.fillStyle='#e9dcae';c.fill();c.lineWidth=8;c.strokeStyle='#fff';c.stroke();const blob=await new Promise(resolve=>source.toBlob(resolve,'image/png'));
 const {createWalletPhotoPicker}=await import('/site-life-wallet.js?document-save-test=1');let ready=0;const errors=[];
 const make=()=>{const picker=createWalletPhotoPicker({onError:message=>errors.push(message),onReady:value=>{if(value)ready+=1}});document.getElementById('host').append(picker.element);return picker};
 const select=picker=>{const transfer=new DataTransfer();transfer.items.add(new File([blob],'synthetic-wallet.png',{type:'image/png'}));picker.input.files=transfer.files;picker.input.dispatchEvent(new Event('change',{bubbles:true}))};
 const cancelled=make();select(cancelled);await wait(()=>cancelled.element.querySelector('[data-scan-state="review"]'),'cancel review');let blocked=false;try{await cancelled.readDataUrl()}catch{blocked=true}cancelled.element.querySelector('.wallet-scan-actions button').click();await sleep(50);const readyAfterCancel=ready;const scannerAfterCancel=Boolean(cancelled.element.querySelector('.wallet-scan-editor'));
 const replaced=make();select(replaced);await wait(()=>replaced.element.querySelector('[data-scan-state="review"]'),'replace review');const replaceButtons=[...replaced.element.querySelectorAll('.wallet-scan-actions button')];replaceButtons.find(button=>button.textContent==='다시 선택').click();await sleep(50);const readyAfterReplace=ready;const scannerAfterReplace=Boolean(replaced.element.querySelector('.wallet-scan-editor'));replaced.destroy();
 const confirmed=make();select(confirmed);const scanner=await wait(()=>confirmed.element.querySelector('[data-scan-state="review"]'),'confirm review');scanner.querySelector('[data-wallet-scan-confirm]').click();await wait(()=>ready===1,'ready callback');const saved=await confirmed.readDataUrl();const preview=confirmed.element.querySelector('.wallet-photo-preview');const scannerAfterConfirm=Boolean(confirmed.element.querySelector('.wallet-scan-editor'));confirmed.destroy();
 out.textContent=JSON.stringify({ok:true,blocked,readyAfterCancel,scannerAfterCancel,readyAfterReplace,scannerAfterReplace,savedJpeg:saved.startsWith('data:image/jpeg;base64,'),previewJpeg:preview.src.startsWith('data:image/jpeg;base64,'),scannerAfterConfirm,networkCalls,closed,privacyText:document.body.textContent.includes('LOTBI 서버로 전송되지 않습니다.'),errors});
}catch(error){out.textContent=JSON.stringify({ok:false,error:String(error?.stack||error)})}
</script></body></html>`;
fs.writeFileSync(FIXTURE,fixture,'utf8');const server=spawn(process.platform==='win32'?'python':'python3',['-m','http.server',String(PORT),'--bind','127.0.0.1'],{cwd:ROOT,stdio:'ignore'});
try{for(let i=0;i<50;i+=1){const ready=spawnSync('curl',['--fail','--silent',`${ORIGIN}/${FIXTURE_REL}`],{timeout:1000});if(ready.status===0)break;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,100);if(i===49)throw new Error('server did not start')}const run=spawnSync(browserPath(),['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--window-size=900,900','--virtual-time-budget=20000','--dump-dom',`${ORIGIN}/${FIXTURE_REL}`],{encoding:'utf8',timeout:40000,maxBuffer:8*1024*1024});if(run.error)throw run.error;const match=run.stdout.match(/<pre id="result">([\s\S]*?)<\/pre>/u);assert.ok(match,run.stderr);const result=JSON.parse(match[1].replaceAll('&quot;','"').replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>'));assert.equal(result.ok,true,result.error);assert.equal(result.blocked,true,'readDataUrl must reject before scan confirmation');assert.equal(result.readyAfterCancel,0,'cancel must not produce a storable image');assert.equal(result.scannerAfterCancel,false,'cancel must remove scanner resources');assert.equal(result.readyAfterReplace,0,'replace must not produce a storable image');assert.equal(result.scannerAfterReplace,false,'replace must remove old scanner resources');assert.equal(result.savedJpeg,true,'only corrected JPEG may enter save flow');assert.equal(result.previewJpeg,true,'picker preview must use corrected JPEG');assert.equal(result.scannerAfterConfirm,false,'confirmation must close scanner editor');assert.equal(result.networkCalls,0,'document processing must make no network request');assert.ok(result.closed>=3,`expected decoded image resources to close, got ${result.closed}`);assert.equal(result.privacyText,true);console.log('LIFE_WALLET_DOCUMENT_SAVE_01 PASS')}finally{server.kill();fs.rmSync(FIXTURE,{force:true})}
