import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {LIFE_SHORTCUTS} from '../site-consumer-sections.js';
const read = file => readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const source = read('site-consumer-sections.js');
const conversation = read('site-conversation.js');
const css = read('site-consumer-design.css');
assert.deepEqual(LIFE_SHORTCUTS.map(item => item.label), ['날씨', '장소', '길찾기', '음식점·생활시설', '축제·행사', '지역생활정보', '지원금·보조금', '공과금 확인']);
assert.equal(new Set(LIFE_SHORTCUTS.map(item => item.id)).size, 8);
assert.ok(LIFE_SHORTCUTS.filter(item => item.id !== 'festivals').every(item => typeof item.prompt === 'string'));
assert.match(LIFE_SHORTCUTS.find(item => item.id === 'bills').prompt, /등록할지/);
for (const label of ['사람 등록', '제휴처 찾아 연결하기']) assert.ok(source.includes(label));
assert.doesNotMatch(source, /\bfetch\(|localStorage|sessionStorage|innerHTML|type = 'file'/);
assert.match(source, /mountLifeWallet\(\{root, authenticated, accountId, sessionExpiresAt\}\)/);
assert.match(source, /action\('사람 등록', null, \{disabled: true\}\)/);
assert.match(source, /role', 'tablist'/);
assert.match(source, /aria-selected/);
assert.match(source, /ArrowLeft.*ArrowRight.*Home.*End/);
assert.match(source, /disposed \|\| current !== generation/);
assert.match(source, /!authenticated/);
assert.match(source, /mounted\?\.dispose\?\.\(\)/);
assert.match(conversation, /onClose: \(\) => mounted\?\.dispose\(\)/);
assert.match(conversation, /mountPetFamilyManager\(\{sessionToken, root, subscription: serverSubscription/);
assert.match(conversation, /onDraft: text => \{ closeSurface\(\); draft\(text\); \}/);
assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(css, /min-height: 44px/);
assert.match(css, /input:focus-visible/);
assert.match(read('site-scam-shield.js'), /scamOutsideBound/);
const scam = read('site-scam-shield.js');
assert.match(scam, /function restoreDialogFocus\(\)/, 'all close paths share visible-trigger focus restoration');
assert.match(scam, /visibleTrigger \? dialogTrigger : document\.querySelector\('\[data-mobile-nav-open\]'\)/, 'a hidden mobile trigger must fall back to the visible menu button');
assert.match(scam, /target\?\.focus\?\.\(\)/);
assert.match(scam, /dialog\.addEventListener\('close', restoreDialogFocus\)/, 'native close restores focus');
assert.match(scam, /dialog\.removeAttribute\('aria-modal'\);\s*restoreDialogFocus\(\);/, 'fallback close restores focus');
console.log('CONSUMER_SECTIONS_02 PASS — entry UX and safety source contracts, not backend E2E');
