import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = file => fs.readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const html = read('index.html');
const js = read('site-conversation.js');
const subscribe = read('subscribe.html');
const expected = ['새 대화', '캘린더', 'Life Wallet', '진위확인', '안심케어', '생활정보', '제휴몰'];
const navs = [...html.matchAll(/<div class="consumer-primary-nav"[^>]*>([\s\S]*?)<\/div>/g)];
assert.equal(navs.length, 2, 'desktop and mobile use the same navigation');
for (const [,nav] of navs) {
  assert.deepEqual([...nav.matchAll(/<button\b[^>]*aria-label="([^"]+)"/g)].map(match => match[1]), expected);
  assert.match(nav, /data-calendar-view="all"/);
  assert.match(nav, /data-scam-open/);
}
assert.match(html, /data-lotbi-avatar-stage/);
assert.match(html, /data-lotbi-avatar-fallback/);
assert.match(html, /lotbi-lockup-160w\.png/);
assert.match(js, /https:\/\/account\.lotbiai\.com\/account/);
assert.match(js, /\['프로필', openProfile\], \['개인테마', openPersonalTheme\], \['설정', openSettings\]/);
assert.match(js, /mountConsumerSection/);
assert.match(js, /workspace: section/);
const calendarSurface = js.slice(js.indexOf('const openCalendar = async'), js.indexOf('const bindCalendarEntries'));
assert.match(calendarSurface, /panel\.classList\.add\('site-calendar-modal', 'site-calendar-chat-popup'\)/);
assert.match(calendarSurface, /installSurfaceBehavior\(backdrop, panel, \{\s*modal: true,/);
assert.doesNotMatch(calendarSurface, /workspace:/, 'Calendar must remain an overlay over the chat');
assert.match(js, /mainScrollHost.inert = true/);
assert.match(js, /mainScrollHost.inert = false/);
assert.match(js, /else if \(!workspace\) trapFocus/);
assert.match(js, /closeSurface\(\); startNewConversation\(\)/);
assert.match(html, /consumer-brand-fallback/);
const consumerSections = read('site-consumer-sections.js');
assert.match(consumerSections, /root\.append\(tabs, body\);[\s\S]*loadCareCounts\(\)[\s\S]*void selectTab\('people'\)/);
assert.doesNotMatch(consumerSections, /긴급한 상황이라면|사람 실종 신고|반려동물 실종 신고/);
assert.match(js, /openFestival/);
assert.match(js, /openLotbiBox/);
assert.match(js, /backLabel: '생활정보로 돌아가기', onBack: \(\) => openConsumerSection\('life'\)/);
assert.match(js, /backLabel: '안심케어로 돌아가기', onBack: \(\) => openConsumerSection\('care'\)/);
assert.match(js, /back.removeEventListener\('click', closeSurface\)/);
for (const text of ['일상을 챙겨주는 AI 생활비서', '생활 전반을 더 많이 맡기는 개인비서', 'LOTBI를 가장 넉넉하게 사용', '9,900원', '19,900원', '39,900원', '프로필 1개', '프로필 5개', '프로필 15개']) assert.ok(subscribe.includes(text));
assert.doesNotMatch(subscribe, /29,900원/);
assert.match(js, /event\.preventDefault\(\); event\.stopPropagation\(\); closeSurface\(\); if \(typeof onBack === 'function'\) onBack\(\)/, 'nested ESC must not also reach the global surface closer');
console.log('CONSUMER_DESIGN_SHELL_01 PASS (source contracts, not live E2E)');
