import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read = file => readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const pages = ['about', 'contact', 'privacy', 'terms', 'account-deletion', 'refund', 'exchange', 'dispute', 'feedback', '404'];
for (const page of pages) {
  const html = read(`${page}.html`);
  assert.match(html, /<body class="consumer-document">/);
  assert.match(html, /site-consumer-documents\.css/);
  assert.match(html, /site-document-navigation\.js[^>]*defer/);
  assert.match(html, /site-static-theme\.css/);
  assert.match(html, /lotbi-brand-logo-light/);
  assert.match(html, /lotbi-brand-logo-dark/);
  assert.ok(html.indexOf('lotbiSavedTheme') < html.indexOf('<link rel="stylesheet"'), `${page} must resolve theme before paint`);
}
const css = read('site-consumer-documents.css');
assert.match(css, /body\.consumer-document/);
assert.match(css, /max-width: 600px/);
assert.match(css, /focus-visible/);
assert.doesNotMatch(css, /linear-gradient|radial-gradient/);
assert.match(css, /\.consumer-document \.legal-table-scroll \{ width: 100%; max-width: 100%; margin: 18px 0 26px; transform: none;/, 'the privacy table container must not widen beyond the legal reading column');
const baseCss = read('styles.css');
assert.match(baseCss, /@media \(max-width: 760px\)/, 'mobile legal table presentation stays available');
assert.match(baseCss, /content: attr\(data-label\)/, 'all seven field labels must remain readable on mobile');
const navigation = read('site-document-navigation.js');
assert.match(navigation, /heading\.textContent/);
assert.match(navigation, /details/);
assert.doesNotMatch(navigation, /fetch\(|localStorage|sessionStorage|innerHTML/);
const sections = read('site-consumer-sections.js');
assert.match(sections, /openLifeDetail\(item\)/);
assert.match(sections, /queryForm\.addEventListener\('submit'/);
assert.match(sections, /event\.preventDefault\(\)/);
assert.match(sections, /if \(disposed\) return/);
assert.match(sections, /root\.replaceChildren\(heading, grid\)/, 'back restores the category list only');
assert.match(sections, /출발지.*서울역/);
assert.match(sections, /목적지.*전주 한옥마을/);
assert.doesNotMatch(sections, /공과금|고지서|납기일/, 'no utility-bill entry until an official integration exists');
assert.doesNotMatch(sections, /fetch\(|type = 'file'|localStorage/);
console.log('CONSUMER_DOCUMENTS_01 PASS — ten public pages and explicit life-information draft flows, source checks only');
