import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const read = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const html = read('index.html');
const core = read('site-core.js');
const conversation = read('site-conversation.js');
const ui = read('site-scam-shield.js');

assert.match(html, /LOTBI 안심확인/);
assert.match(html, /“롯비야, 이거 진짜야\?”/);
assert.equal((html.match(/data-scam-open/gu) || []).length, 2, 'desktop and mobile navigation must expose one compact Scam Shield entry each');
assert.doesNotMatch(html, /class="scam-shield-card"/, 'Scam Shield must not reintroduce a marketing section into White Home');
assert.match(html, /accept="image\/jpeg,image\/png,image\/webp,\.txt,text\/plain,\.html,\.htm,text\/html,application\/pdf"/);
assert.match(html, /이미 눌렀거나 정보를 입력했어요/);
assert.match(core, /\/v2\/scam-shield\/cases/);
assert.match(core, /untrusted_file_execution !== false/);
assert.match(core, /public_file_upload_to_third_party !== false/);
assert.match(ui, /확인이 더 필요해요/);
assert.doesNotMatch(ui, /안전합니다|안전해요/);
assert.match(conversation, /analyzeScamShield\(sessionToken, detail\.formData\)/);
assert.match(ui, /왜 그렇게 보나요\?/);
assert.match(ui, /아직 확인 안 된 내용/);
assert.match(ui, /지금 하실 일/);
assert.match(ui, /하지 마세요/);
assert.match(ui, /typeof dialog\.showModal === 'function'/, 'native dialog support must remain the preferred path');
assert.match(ui, /dialog\.setAttribute\('open', ''\)/, 'browsers without the dialog API must still open Scam Shield');
assert.match(ui, /typeof dialog\.close === 'function'/, 'native dialog close must remain the preferred path');
assert.match(ui, /dialog\.removeAttribute\('open'\)/, 'fallback dialog must be closable without the dialog API');
assert.match(ui, /lotbi:home-shell-hydrated/, 'login callback hydration must rebind Scam Shield to the replaced home DOM');
assert.match(ui, /dataset\.scamBound/, 'hydration rebinding must remain idempotent');
console.log('SITE-SCAM-SHIELD-MVP-01 PASS');
